// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc4LgbgEeZClmqer2BDK46rlNiV-SBBlg',
    appId: '1:942800220603:web:e2c1f5904dbdc81222149e',
    messagingSenderId: '942800220603',
    projectId: 'sw1-p2',
    authDomain: 'sw1-p2.firebaseapp.com',
    storageBucket: 'sw1-p2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVed5Wjub7Wbz66ZJ43AqpBbnPVXA18dg',
    appId: '1:942800220603:android:af5af5edc666910d22149e',
    messagingSenderId: '942800220603',
    projectId: 'sw1-p2',
    storageBucket: 'sw1-p2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE52-TSAPLOqeclP-ntldlDrOUUx-DVcg',
    appId: '1:942800220603:ios:82457a7b45e05c0422149e',
    messagingSenderId: '942800220603',
    projectId: 'sw1-p2',
    storageBucket: 'sw1-p2.appspot.com',
    iosBundleId: 'com.example.fireBaseEvento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE52-TSAPLOqeclP-ntldlDrOUUx-DVcg',
    appId: '1:942800220603:ios:82457a7b45e05c0422149e',
    messagingSenderId: '942800220603',
    projectId: 'sw1-p2',
    storageBucket: 'sw1-p2.appspot.com',
    iosBundleId: 'com.example.fireBaseEvento',
  );
}
